#ifndef __NPD_INTF_H__
#define __NPD_INTF_H__

#define NPD_INTF_SAVE_STATIC_ARP_MEM (65*1024)

enum INTF_STATUS_E {
	INTF_STATE_DOWN_E = 0,
	INTF_STATE_UP_E,
	INTF_STATE_MAX
};


#define MAX_L3INTF_NUMBER NPD_L3INTF_SIZE

#define MAX_L3INTF_ADDR  (MAX_L3INTF_NUMBER * MAX_IP_COUNT)
#define NPD_L3INTF_ADDR_HASH_SIZE  (MAX_L3INTF_NUMBER * MAX_IP_COUNT)

#define INVALID_HOST_IP 0xFFFFFFFF
#define INVALID_L3_INTF_VID 0xffffffff
#define INVALID_PORT_INTF 0xffffffff

#define MAX_IFNAME_LEN 20

#endif
