#ifndef __NPD_FACILITY_H__
#define __NPD_FACILITY_H__


#define TRUNK_FACILITY 24<<3
#define FDB_FACILITY 25<<3
#define ACL_DRV_FACILITY 26<<3
#define ETH_PORT_FACILITY 27<<3
#define HASH_FACILITY 28<<3
#define INTF_FACILITY 29<<3
#define PVLAN_FACILITY 30<<3
#define VLAN_FACILITY 31<<3
#define IGMP_FACILITY 32<<3
#define ROUTE_FACILITY 33<<3
#define ARP_SNOOP_FACILITY 34<<3
#define ACL_FACILITY 35<<3
#define QOS_FACILITY 36<<3
#define CSLOT_FACILITY 37<<3
#define ENGINE_FACILITY 38<<3
#define ESLOT_FACILITY 39<<3
#define MIRROR_FACILITY 40<<3
#define DBUS_FACILITY 41<<3
#define PRODUCT_FACILITY 42<<3
#define RSTP_FACILITY 43<<3
#define MAIN_FACILITY 44<<3
#define DLDP_FACILITY 45<<3
#define DHCP_SNOOP_FACILITY 46<<3
#define ASD_FACILITY 47<<3
#define ASIC_FACILITY 48<<3

#define SYSLOG_LOG_EMERG    LOG_EMERG
#define SYSLOG_LOG_ALERT    LOG_ALERT
#define SYSLOG_LOG_CRIT     LOG_CRIT
#define SYSLOG_LOG_ERR      LOG_ERR
#define SYSLOG_LOG_WARNING  LOG_WARNING
#define SYSLOG_LOG_NOTICE   LOG_NOTICE
#define SYSLOG_LOG_INFO     LOG_INFO
#define SYSLOG_LOG_DEBUG    LOG_DEBUG


#endif				
