#ifndef _UDLD_TIMER_H_
#define _UDLD_TIMER_H_

#define UDLD_ECHO_TIMER_DEFAULT			15
#define UDLD_ECHO_TIMER_MIN				5
#define UDLD_ECHO_TIMER_MAX				60

#define UDLD_ENHANCED_TIMER_DEFAULT		2
#define UDLD_ENHANCED_TIMER_MIN			1
#define UDLD_ENHANCED_TIMER_MAX			8

#define UDLD_ENHANCED_RETRY_TIMES		8
#define UDLD_ENHANCED_RETRY_MIN			4
#define UDLD_ENHANCED_RETRY_MAX			12

#define UDLD_ECHO_TIMEOUT_DEFAULT		1
#define UDLD_ECHO_TIMEOUT_MIN			1
#define UDLD_ECHO_TIMEOUT_MAX			5

#define UDLD_RECOVER_TIMER_DEFAULT		30
#define UDLD_RECOVER_TIMER_MIN			10
#define UDLD_RECOVER_TIMER_MAX			60


#define UDLD_INVALID_TIMER				0xFF

int udld_timer_init();


#endif

