#ifndef __MACRO_SDK_DRIVER_H__
#define __MACRO_SDK_DRIVER_H__


enum module_driver_type_e
{
	MODULE_DRIVER_NONE,
	MODULE_DRIVER_NBM,
	MODULE_DRIVER_NAM_BCM,
	MODULE_DRIVER_NAM_CPSS,
	MODULE_DRIVER_NAM_CTC,
	MODULE_DRIVER_NAM_ATHEROS
};


#endif
