#ifndef __MNG_ARPSNOOP_H__
#define __MNG_ARPSNOOP_H__

#define IP_ARP_INSPECTION_VALIDATE_SMAC_CHECK 1
#define IP_ARP_INSPECTION_VALIDATE_DMAC_CHECK 2
#define IP_ARP_INSPECTION_VALIDATE_IP_CHECK   4

#endif

